src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

# from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

from .views import home_page, contact_page, login_page, register_page	

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url('home/', home_page),
    # url('contact/', contact_page),
    # url('login/', login_page),
    # url('register/', register_page),
    # url('products/', product_list),

    path('admin/', admin.site.urls),
    path('home/', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('products/', include("products.urls", namespace="products")),
    path('register/', register_page, name='register'),
    path('search/', include("search.urls", namespace="search")),
    # path('products/', product_list),
    # path('products/<int:id>/', product_detail),
    # path('featured/', product_featured_list),
    # path('products/<slug:slug>/', product_slug_detail),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path

from .views import (
    product_list, 
    product_detail,
    product_featured_list,
    product_slug_detail,
    )
app_name = 'products'
urlpatterns = [
    path('', product_list.as_view(), name='list'),
    path('<int:id>/', product_detail.as_view()),
    path('featured/', product_featured_list),
    path('<slug:slug>/', product_slug_detail, name='detail'),
]

src/search/urls.py
from django.urls import path

from .views import (
    product_list, 
    product_detail,
    product_featured_list,
    product_slug_detail,
    )
app_name = 'products'
urlpatterns = [
    path('', product_list.as_view(), name='list'),
    path('<int:id>/', product_detail.as_view()),
    path('featured/', product_featured_list),
    path('<slug:slug>/', product_slug_detail, name='detail'),
]

src/products/models.py
import uuid
import os
from django.db import models
from django.db.models.signals import pre_save,post_save
from .utils import unique_slug_generator
from django.urls import reverse

def get_file_path(instance, filename):
	ext = filename.split('.')[-1]
	filename = "%s.%s" % (uuid.uuid4(), ext)
	return os.path.join('products/', filename)

# def get_filename_ext(filepath):
# 	base_name = os.path.basename(filepath)
# 	name, ext = os.path.splitext(base_name)
# 	return name, ext

# def upload_image_path(instance, filename):
# 	print(instance)
# 	print(filename)
# 	new_filename = random.randint(1, 8342233)
# 	name, ext = get_filename_ext(filename)
# 	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
# 	return "products/{new_filename}/{final_filename}".format(
# 		new_filename=new_filename,
# 		final_filename=final_filename
# 		)

class Product(models.Model):
	title 		= models.CharField(max_length=120)
	slug		= models.SlugField(unique=True, blank=True)
	description = models.TextField()
	price 	 	= models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
	image		= models.FileField(upload_to=get_file_path, null=True, blank=True)
	featured	= models.BooleanField(default=False)
	active		= models.BooleanField(default=True)
	timestamp	= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		# return "/products/{slug}/".format(slug=self.slug)
		return reverse("products:detail", kwargs={"slug": self.slug})

def product_pre_save_receiver(sender,instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

src/search/models.py
from django.db import models

# Create your models here.

src/ecommerce/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.Form):
	fullname = forms.CharField(
		widget=forms.TextInput(
			attrs={
			"class": "form-control",
			"placeholder": "Your full name"
			}))
	email = forms.EmailField(
		widget=forms.EmailInput(
			attrs={
			"class": "form-control",
			"placeholder": "Your email address"
			}))

	content = forms.CharField(
		widget=forms.Textarea(
			attrs={
			"class": "form-control",
			"placeholder": "Your message"
			}))

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(
		widget=forms.PasswordInput())


class RegisterForm(forms.Form):
	username = forms.CharField()
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

	def clean_username(self):
		username = self.cleaned_data.get('username')
		qs = User.objects.filter(username=username)
		if qs.exists():
			raise forms.ValidationError('Username already taken')
		return username

	def clean_email(self):
		email = self.cleaned_data.get('email')
		qs = User.objects.filter(email=email)
		if qs.exists():
			raise forms.ValidationError('Email already taken')
		return email

	def clean(self):
		data = self.cleaned_data
		password = self.cleaned_data.get('password')
		password2 = self.cleaned_data.get('password2')
		if password2 != password:
			raise forms.ValidationError("Passwords must match")
		return data

src/ecommerce/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import ContactForm, LoginForm, RegisterForm

def home_page(request):
	context = {
		"title": "Ecommerce",
		"brand": "eZCommerce",
		"content": "Welcome to EzCommerce Homepage",
		"premium_content": "YEAAAHHH boi!",
	}
	return render(request, "home_page.html", context)

def contact_page(request):
	contact_form = ContactForm(request.POST or None)
	context = {
		"title": "Contact",
		"brand": "eZCommerce",
		"content": "Contact Page",
		"form": contact_form
	}
	if contact_form.is_valid():
		print(contact_form.cleaned_data)

	# if request.method == "POST":
	# 	# print(request.POST)
	# 	print(request.POST.get('fullname'))
	# 	print(request.POST.get('email'))
	# 	print(request.POST.get('content'))
	return render(request, "contact/view.html", context)

def login_page(request):
	form = LoginForm(request.POST or None)
	context = {
		"form": form
	}
	print("User logged in")
	print(request.user.is_authenticated)
	if form.is_valid():
		# print(form.cleaned_data)
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			# Redirect to a success page.
			# context['form'] = LoginForm()
			return redirect("/login")
		else:
			# Return an 'invalid login' error message.
			print("Error")

	
	return render(request,"auth/login.html", context)


def register_page(request):
	form = RegisterForm(request.POST or None)
	context = {
		"form": form
	}
	if form.is_valid():
		print(form.cleaned_data)
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		email = form.cleaned_data.get("email")
		new_user = User.objects.create_user(username, email, password)		
		print(new_user)
		
	return render(request, "auth/login.html", context)

src/products/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from .models import Product

class product_list(ListView):
	queryset = Product.objects.all()
	template_name = "products/list.html"

# def product_list(request):
# 	queryset = Product.objects.all()
# 	context = {
# 		'object_list':queryset
# 	}
# 	return render(request, "products/list.html", context)

class product_detail(DetailView):
	template_name = "products/detail.html"

	def get_object(self, *args, **kwargs):
		request = self.request
		id = self.kwargs.get('id')
		instance = get_object_or_404(Product, id=id)
		return instance

# def product_detail(request, id=None):
	
# 	instance = get_object_or_404(Product, id=id)
# 	print(instance)
# 	context = {
# 		'object':instance
# 	}
# 	return render(request, "products/detail.html", context)

def product_featured_list(request):
	queryset = Product.objects.filter(featured=True)
	context = {
		'object_list':queryset
	}
	return render(request, "products/list.html", context)

def product_slug_detail(request, slug=None):
	
	instance = get_object_or_404(Product, slug=slug, active=True)
	print(instance)
	context = {
		'object':instance
	}
	return render(request, "products/detail.html", context)

src/search/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'base/css.html' %}
  </head>
  <body>
    {% include 'base/navbar.html' %}

    <div class="container">
      {% block content %}{% endblock %}
    </div>
  	
    {% include 'base/js.html' %}
  </body>
</html>

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}' >

src/templates/base/js.html
{% load static %}
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'products:list' as products_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">{{ brand }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == products_url %} active {% endif %}">
        <a class="nav-link" href="{{ products_url }}">Products</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == login_url %} active {% endif %}">
        <a class="nav-link" href="{{ login_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %} active {% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %} active {% endif %}">
        <a class="nav-link" href="{{ login_url }}">Register</a>
      </li>      
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

src/templates/contact/view.html
{% extends "base.html" %}

{% block content %}
<title>{{ title }}</title>
<div class='text-center'>
<h1>{{ content }}</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="col-sm-6 col-12">
        <form method="POST"> {% csrf_token %}
          {{ form }}
          <button type="submit" class="btn btn-primary">Submit</button>              
        </form>
        
      </div>
    </div>
  </div>
</div>
{% endblock %}
   

src/templates/home_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<title>{{ title }}</title>

  <div class='text-center'>
    <img src="{% static 'img/ocd.png' %}" class="img-fluid"/>
    <p>{{ content }}</p>
  </div>
  {% if request.user.is_authenticated %}
    <div class='text-center'>
      <h1>{{ premium_content }}</h1>
    </div>
  {% endif %}

{% endblock %}

src/templates/products/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	
<title>{{ title }}</title>
<div class='text-center'>
<h1>{{ content }}</h1>
</div>

  <div class="row">
    <div class="col">
    	{{ object.title }} <br/>
		{{ object.description|linebreaks }} <br/>
		{{ object.timestamp }} <br/>

		{% if object.image %}
			<img src="{{ object.image.url }}" class="img-fluid">
		{% endif %}
    </div>
  </div>

{% endblock %}

src/templates/products/list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	{% for obj in object_list%}
		<div class="col">
			{% include 'products/snippets/card.html' %}
		</div>
	{% endfor %}	
	
</div>


{% endblock %}

src/templates/products/snippets/card.html
<div class="card" style="width: 18rem;">
	{% if obj.image %}
  		<img class="card-img-top" src="{{ obj.image.url }}" alt="Card image cap">
  	{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ obj.title }}</h5>
    <p class="card-text">{{ obj.description|truncatewords:14 }}</p>
    <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">View</a>
   
  </div>
</div>